name: Ping Url
author: olutosinbamigboye
description: Ping url until maximum trials have exceeded. If result is not 200 until then, fail the action
inputs:
  url: # Input_URL for shell script in Python
    required: true
    description: URL to ping
  max_trials: #Input_Max_Trials for shell script in Python
    required: false
    default: '10'
    description: Maximum number of trials to ping the URL
  delay:
    required: true
    default: '1'
    description: Delay between trials in milliseconds

outputs:
  url-reachable:
    description: Website is reachable
    value: ${{ steps.ping-url.outputs.website-reachable }}
runs:
  using: docker
  image: Dockerfile

