name: Update NPM Dependencies
author: olutosinbamigboye
description: Checks if there are updates to NPM packages, and creates a PR with the updated package*.json files
inputs:
  base-branch:
    description: Base branch from which to check for updates
    default: main
    required: false
  target-branch:
    default: update-dependencies
    description: Branch to which the PR will be created
    required: false

  working-directory:
    description: Directory in which to run the action
    required: true

  gh-token:
    description: Github token for authentication to create PRs. Must have write access to the repository
    required: true

  debug:
    description: Enable debug logging
    required: 'false'
    type: boolean
uns:
  using: node20
  main: index.js

